# Generated by Django 5.0.1 on 2024-01-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationalities', '0002_alter_nacionalidades_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nacionalidades',
            name='img',
            field=models.ImageField(upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='nacionalidades',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
