# Generated by Django 5.0.1 on 2024-01-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_lineup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Persond',
        ),
    ]
