# Generated by Django 5.0.1 on 2024-01-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_lineup', '0003_nice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NICE',
        ),
        migrations.DeleteModel(
            name='Persond',
        ),
    ]
