# Generated by Django 5.0.1 on 2024-01-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_lineup', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persond',
        ),
    ]
