# Generated by Django 5.0.1 on 2024-01-17 23:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('create_lineup', '0008_delete_persond'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalacoes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
