# Generated by Django 5.0.1 on 2024-01-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_lineup', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalacoes',
            name='img',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
