# Generated by Django 5.0.1 on 2024-01-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
