# Generated by Django 5.0.1 on 2024-01-17 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_jogadores', models.IntegerField(default=11, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(1)])),
                ('nome', models.CharField(max_length=200)),
                ('p1x', models.IntegerField()),
                ('p1y', models.IntegerField()),
                ('p2x', models.IntegerField()),
                ('p2y', models.IntegerField()),
                ('p3x', models.IntegerField()),
                ('p3y', models.IntegerField()),
                ('p4x', models.IntegerField()),
                ('p4y', models.IntegerField()),
                ('p5x', models.IntegerField()),
                ('p5y', models.IntegerField()),
                ('p6x', models.IntegerField()),
                ('p6y', models.IntegerField()),
                ('p7x', models.IntegerField()),
                ('p7y', models.IntegerField()),
                ('p8x', models.IntegerField()),
                ('p8y', models.IntegerField()),
                ('p9x', models.IntegerField()),
                ('p9y', models.IntegerField()),
                ('p10x', models.IntegerField()),
                ('p10y', models.IntegerField()),
                ('p11x', models.IntegerField()),
                ('p11y', models.IntegerField()),
            ],
        ),
    ]
