# Generated by Django 5.0.1 on 2024-01-19 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_jogadores_nacionalidade_alter_jogadores_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.AlterField(
            model_name='jogadores',
            name='nacionalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.nacionalidades'),
        ),
    ]
