# Generated by Django 5.0.1 on 2024-01-19 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionalidades', '0001_initial'),
        ('players', '0003_nacionalidades_alter_jogadores_nacionalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogadores',
            name='nacionalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nacionalidades.nacionalidades'),
        ),
        migrations.DeleteModel(
            name='Nacionalidades',
        ),
    ]
