# Generated by Django 5.0.1 on 2024-01-19 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('players', '0006_alter_jogadores_nacionalidade_delete_nacionalidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogadores',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.times'),
        ),
        migrations.DeleteModel(
            name='Times',
        ),
    ]
